# -*- coding: utf-8 -*-
"""CN_LAB-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AkJmPZTVGFveG2VjALAohRlVdFc1EMns

#**COMPUTER NETWORKS LAB - 5**

*Write a program (in a language of your choice) to find out the following things as output from given IP address:*
1. Class of IP address
2. Number of bits of NetID portion
3. Number of bits of HostID portion
4. Number of networks supported by the respective class
5. Number of hosts supported per network for the respective class of IP address
6. Start range and end range of given class of IP address.
7. Subnet Mask address
"""

import math

def get_ip_class(first_octet):
    if 1 <= first_octet <= 126:
        return "A"
    elif 128 <= first_octet <= 191:
        return "B"
    elif 192 <= first_octet <= 223:
        return "C"
    elif 224 <= first_octet <= 239:
        return "D"
    elif 240 <= first_octet <= 255:
        return "E"
    else:
        return "Invalid"

def ip_details(ip):
    parts = ip.split(".")

    if len(parts) != 4:
        print("Invalid IP Address")
        return

    try:
        first_octet = int(parts[0])
    except:
        print("Invalid IP Address")
        return

    ip_class = get_ip_class(first_octet)

    if ip_class == "Invalid":
        print("Invalid IP Address")
        return

    print("\nIP Address:", ip)
    print("Class of IP Address:", ip_class)

    if ip_class == "A":
        net_bits = 8
        host_bits = 24
        networks = 2**7 - 2
        hosts = 2**24 - 2
        start_range = "1.0.0.0"
        end_range = "126.255.255.255"
        subnet_mask = "255.0.0.0"

    elif ip_class == "B":
        net_bits = 16
        host_bits = 16
        networks = 2**14
        hosts = 2**16 - 2
        start_range = "128.0.0.0"
        end_range = "191.255.255.255"
        subnet_mask = "255.255.0.0"

    elif ip_class == "C":
        net_bits = 24
        host_bits = 8
        networks = 2**21
        hosts = 2**8 - 2
        start_range = "192.0.0.0"
        end_range = "223.255.255.255"
        subnet_mask = "255.255.255.0"

    elif ip_class == "D":
        print("Class D is reserved for Multicasting.")
        return

    elif ip_class == "E":
        print("Class E is reserved for Experimental purposes.")
        return

    print("Number of NetID bits:", net_bits)
    print("Number of HostID bits:", host_bits)
    print("Number of networks supported:", networks)
    print("Number of hosts per network:", hosts)
    print("Start range:", start_range)
    print("End range:", end_range)
    print("Default Subnet Mask:", subnet_mask)


# ===== Main Program =====
ip_input = input("Enter an IPv4 address: ")
ip_details(ip_input)